### ISSUE TITLE
Open standard autohotkey chm-help file with a command near keyboard caret

### ISSUE THREAD

**Issue by helperman** [vscode-autohotkey/ahkpp#327] opened 2023-01-29 20:37 UTC
Here is a how this feature should work (after pressing F1, for ex):
![00000071](https://user-images.githubusercontent.com/8351863/215354506-84f0c57f-e604-4e19-bbee-2c3cd6c20d05.gif)

**Comment by mark-wiemer** [comment] 2023-01-29 20:54
Thanks for the input, @helperman, but I haven't seen significant changes since #78 was opened. This is a duplicate of that one, and I'm closing it as such. Feel free to comment on the original with any insights you may have to implement this in standard JavaScript with the VS Code API.

**Closed by mark-wiemer** 2023-01-29 20:54 UTC
Labels: enhancement
